### ISSUE TITLE
Readme error?

### ISSUE THREAD

**Issue by MARTIMM** [lizmat/P5times#2]
Hi,
I think the remark that the times() function returns times in seconds is wrong. It should be in microseconds.

**Comment by lizmat** [comment]
From perldoc -f times:

    times   Returns a four-element list giving the user and system times in
            seconds for this process and any exited children of this
            process.

                my ($user,$system,$cuser,$csystem) = times;

            In scalar context, "times" returns $user.

            Children's times are only included for terminated children.

            Portability issues: "times" in perlport.

**Comment by MARTIMM** [comment]
Yes, I've seen that too, but looking in your code I see multiplications of 1e6, then adding some micro secs and not converting them back to secs (if I understood it alright). Anyways, the results are large enough to be microseconds...

```
nqp::atpos_i(@rusage, nqp::const::RUSAGE_UTIME_SEC) * 1000000
        + nqp::atpos_i(@rusage, nqp::const::RUSAGE_UTIME_MSEC),
```
I would like you to keep it that way (less conversions) and only change the text.

Alvast dank je wel

**Comment by lizmat** [comment]
Added the this Porting Caveat:

    =head2 Microseconds vs Seconds

    Due to a misunderstanding, it was found that the the C<times> function returns
    B<microseconds> versus seconds (as the original Perl version does).  This was
    only found after two years of this module's existence, and deemed much more
    useful in the Raku context.

    Therefore it was decided to keep this behaviour in December 2020.

New version on its way to the ecosystem now.  Thanks for the spot!
